# 公共配置
spring:
  application:
    name: test-2
  # 默认 dev 环境
  profiles:
    active: dev
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test-2
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置，然后取消注释
  #  redis:
  #    database: 1
  #    host: localhost
  #    port: 6379
  #    timeout: 5000
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 1000MB
      max-request-size: 1000MB

  #rabbitmq配置
#  rabbitmq:
#    host: 192.168.126.130
#    username: guest
#    password: guest
#    virtual-host: /
#    port: 5672

server:
  tomcat:
    max-swallow-size: 1000MB
  address: 0.0.0.0
  port: 8082
  servlet:
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 七牛云对象存储
qiniu:
  kodo:
    # 配置accessKey
    accessKey: xTh69dyj5hZk_WW_PO3_MHX56KVPkjJmfbmIOhcX
    # 配置secretKey
    secretKey: kNjWFoLykbqC-P7XcwzyKjgOVCQ7LjOtYcgumpfV
    # 配置空间名称
    bucket: idoltrainer
    zone: huanan # 存储区域
    # 配置域名
    domain: s3159m8av.hn-bkt.clouddn.com



